name: Ежедневный анализ акций

on:
  schedule:
        - cron: '30 20 * * 3,5'
  workflow_dispatch:

jobs:
  run-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Получить код
        uses: actions/checkout@v4
      
      - name: Установить Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Установить зависимости
        run: |
          pip install --upgrade pip
          pip install yfinance pandas numpy requests
      
      - name: Запустить анализ
        run: python stock_analyzer.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          
     - name: Сохранить отчёт
        uses: actions/upload-artifact@v4
        with:
          name: stock-report
          path: stock_report_*.txt
